### ISSUE TITLE
Add support for serializing array of objects

### ISSUE THREAD

**Issue by jsbattig** [Sovos-Compliance/mongo-delphi-driver#40]
Currently Delphi driver only supports de/serializing arrays of primitive types. Objects are not supported.

**Comment by jsbattig** [comment]
The way to handle array of objects with Delphi relies on using custom de/serializers. It will be nice to have a generic one that can do this natively

**Comment by oleksiivorobiov** [comment]
Done in this commit https://github.com/alexeyvo/mongo-delphi-driver/commit/f9577d14915d8a9c4a4657f8089702e597e0e79a

**Comment by oleksiivorobiov** [comment]
This can be closed
